config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get "auth/login"
    end
  end

  devise_for :users

  resources :projects do
    member do
      get :contributions
      get :manage_users
      post :manage_users, to: "projects#add_and_remove_users"
      namespace :contribution do
        resources :images, only: [:new, :create, :update]
        resources :texts,  only: [:new, :create, :update]
      end
      # resources :contribution_images, as: :images, only: [:new, :create, :update], path: :images
      # resources :contribution_texts,  as: :text,   only: [:new, :create, :update], path: :text
    end
  end

  get "pages/test"

  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
module Contribution
  def self.table_name_prefix
    'contribution_'
  end
end

app/models/contribution/image.rb
require "ContributionImageUploader"

class Contribution::Image < ApplicationRecord
  include ::ContributionImageUploader[:image]

  belongs_to :project
  belongs_to :user
end

app/models/contribution/text.rb
class Contribution::Text < ApplicationRecord
  validates :body, presence: true
  validates :user_id, presence: true
  validates :project_id, presence: true

  belongs_to :project
  belongs_to :user
end

app/models/profile.rb
require "ProfileImageUploader"

class Profile < ApplicationRecord
  include ::ProfileImageUploader[:image]

  belongs_to :user, touch: true
end

app/models/project.rb
require "ProjectImageUploader"

class Project < ApplicationRecord
  include ::ProjectImageUploader[:image]

  has_many :projects_users, dependent: :destroy
  has_many :users, through: :projects_users

  has_many :contributed_texts, class_name: "Contribution::Text", dependent: :destroy
  has_many :contributed_images, class_name: "Contribution::Image", dependent: :destroy

  def admins
    users.merge(ProjectsUser.admin)
  end

  def collaborators
    users.merge(ProjectsUser.collaborator)
  end

  def contributions
    contributions = Array.new

    contributions << contributed_texts
    contributions << contributed_images

    contributions.flatten
  end
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  enum project_role: [:collaborator, :admin]

  belongs_to :project, touch: true
  belongs_to :user
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  enum project_role: [:collaborator, :admin]

  belongs_to :project, touch: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  has_many :projects_users, dependent: :destroy
  has_many :projects, through: :projects_users
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApplicationController
  http_basic_authenticate_with name: "user", password: "password"
  def login
    render json: { token: "abc123" }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contribution/images_controller.rb
class Contribution::ImagesController < ApplicationController
  def new
    form Contribution::Image::Create
  end

  def create
    run Contribution::Image::Create do |_op|
      # valid operation
      return redirect_to project_path(@model.project)
    end

    render action: :new
  end
end

app/controllers/contribution/texts_controller.rb
class Contribution::TextsController < ApplicationController
  def new
    form Contribution::Text::Create
  end

  def create
    run Contribution::Text::Create do |_op|
      # valid operation
      return redirect_to project_path(@model.project)
    end

    render action: :new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def test
    Project::InviteUsers.call(
      project: {
        id: 1,
        users: [{ email: "sidious@galactic.empire" }, { email: "vader@galactic.empire" }]
      }
    )

    render nothing: true
  end

  private

  def seed_image(file_name)
    File.open(File.join(Rails.root, "/app/assets/images/seed/#{file_name}.jpg"))
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    present Project::Index
    @projects = @model
  end

  def contributions; end

  def show
    present Project::Update
    @project = @model
  end

  def new
    form Project::Create
  end

  def create
    run Project::Create do |_op|
      # valid operation
      return redirect_to manage_users_project_path(@model)
    end

    render action: :new
  end

  def manage_users
    form Project::ManageUsers
  end

  def add_and_remove_users
    run Project::ManageUsers do |_op|
      return redirect_to project_path(@model)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contribution/images/_image.html.erb
<div class="card">
    <%= image_tag image.image_url(:medium), class: 'card-img-top img-fluid', size: '400x200' %>
    <div class="card-block">
        <% if image.comment.present? %>
          <p class="card-text"><%= image.comment %></p>
        <% end %>
        <p class="card-text"><small class="text-muted">Eingereicht von <emph><%= image.user.profile.nickname %></emph> <%= timeago_tag image.created_at, force: true %></small></p>
    </div>
</div>

app/views/contribution/images/new.html.erb
<div class="container-narrow">
  <%= simple_form_for @form, html: { class: "form-horizontal" } do |f| %>
    <%= f.input :image, as: :file%>
    <%= f.input :copyright %>
    
    <%= f.submit %>
  <% end %>
</div>

app/views/contribution/texts/_text.html.erb
<div class="card card-block">
    <blockquote class="card-blockquote">
        <p><%= text.body.html_safe %></p>
        <footer>
            <small class="text-muted">
                Eingereicht von <emph><%= text.user.profile.nickname %></emph> <%= timeago_tag text.created_at, force: true %>
            </small>
        </footer>
    </blockquote>
</div>

app/views/contribution/texts/new.html.erb
<div class="container-narrow">
  <%= simple_form_for @form, html: { class: "form-horizontal" } do |f| %>
    <%= f.trix_editor :body, input_html: { rows: 20 } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ScienceStreams</title>
        <%= csrf_meta_tags %>
        <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700' rel='stylesheet' type='text/css'>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <%= render 'shared/navbar' %>
        <%= yield %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= timeago_script_tag %>
    </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/projects/_project.html.erb
<div class="project">
  <div class="project-details">
    <h4 class="project-details__title"><%= project.title %></h4>
  </div>
  <%= image_tag project.image_url(:original), class: 'project__image' %>
  <div class="project-details">
    <p class="project-details__description"><%= truncate project.description, length: 255 %></p>
    <%= link_to 'Projekt ansehen', project_path(project), class: 'project-details__view-project-button' %>
  </div>
</div>

app/views/projects/contributions.html.erb
<div class="container">
    <div class="contributions-list">
      <% 5.times do %>
        <%= render @contributions %>
      <% end %>
    </div>
</div>

app/views/projects/form/_user_fields.html.erb
<div class="nested-fields row">
    <div class="col-xs-8">
        <%= f.input :email, readonly: f.object.persisted? %>
        <%= f.hidden_field :_destroy %>
        <%= f.hidden_field :id %>
    </div>

    <div class="col-xs-4">
        <%= link_to_remove_association "Remove User", f %>
    </div>
</div>

app/views/projects/index.html.erb
<div class="container">
    <div class="projects-list">
      <%= render @projects %>
    </div>
</div>

app/views/projects/manage_users.html.erb
<div class="container-narrow">
  <h1>Invite some users to <%= @model.title %></h1>

  <%= simple_form_for @form, url: manage_users_project_path, method: :post, html: { class: "form-horizontal" } do |f| %>
    <div id="users">
      <%= f.simple_fields_for :users  do |users| %>
        <%= render "projects/form/user_fields", f: users %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'Add User', f, :users, partial: "projects/form/user_fields" %>
      </div>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container-narrow">
  <%= simple_form_for @form, html: { class: "form-horizontal" } do |f| %>
    <%= f.input :image, as: :file%>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :about_us, as: :text %>
    <%= f.input :slug %>

    <%= f.submit %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container">
    <h1><%= @project.title %></h1>


    <ul class="project-users">
        <%= render @project.users %>
    </ul>

    <br>

    <div class="dropdown float-right">
      <a class="btn btn-secondary dropdown-toggle" id="project-add-contribution" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Add Contribution
      </a>

      <div class="dropdown-menu" aria-labelledby="project-add-contribution">
        <%= link_to 'Add Image', new_contribution_image_path, class: 'dropdown-item' %>
        <%= link_to 'Add Text', new_contribution_text_path, class: 'dropdown-item' %>
      </div>
    </div>

</div>

<div class="project-about-container--full">
    <div class="project-about">
        <div class="project-about__icon">
            <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-info fa-stack-1x fa-inverse"></i>
            </span>
        </div>
        <div class="project-about__description">
            <h1>Über <%= @project.title %></h1>
            <p><%= @project.description %></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="contributions-list">
        <%= render @project.contributions %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav>
    <%= link_to projects_path, class: 'logo' do %>
        <%= image_tag 'logo.png' %>
    <% end %>
    <ul>
        <li class="projects">
          <a data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Death star</a>
          <div class="project-selector" aria-labelledby="Preview">
            <% Project.all.each do |project| %>
              <%= link_to project.title, '#' %>
            <% end %>
          </div>
        </li>
        <li class="user">
          <a data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">@nickname</a>
          <div class="user-info" aria-labelledby="Preview">
            <span>Signed in as <b>@nickname</b></span>
            <div class="dropdown-divider"></div>
            <a href="#">Dashboard</a>
            <a href="#">Your Profile</a>
            <a href="#">Help</a>
            <div class="dropdown-divider"></div>
            <a href="#">Logout</a>
          </div>
        </li>
    </ul>
</nav>

app/views/users/_user.html.erb
<li>
  <%= image_tag user.profile.image_url(:thumb), class: 'project-users__profile-image project-users__profile-image--admin' %>
</li>